name: Publish to TestPyPI

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '.github/workflows/test-publish.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build pytest

      - name: Install package in editable mode
        run: pip install -e .

      - name: Run tests with pytest
        run:  pytest tests/unit/ -v -m "not functional"

      - name: Build package
        run: python -m build

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/

      - name: Create test tag
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag test-release-$(date +'%Y%m%d%H%M%S')
          git push origin --tags
